/* Gerado por scripts/build-email-export.py. Não edite à mão. */
window.AsimovEmailTemplates = [
  {
    "id": "design-system--em-001-claro",
    "caminho": "design-system/em-001-claro.html",
    "sistema": "Aura",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": null,
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system--em-001-escuro",
    "caminho": "design-system/em-001-escuro.html",
    "sistema": "Aura",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": null,
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system--em-005-claro",
    "caminho": "design-system/em-005-claro.html",
    "sistema": "Aura",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": null,
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system--em-005-escuro",
    "caminho": "design-system/em-005-escuro.html",
    "sistema": "Aura",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": null,
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system--em-022-claro",
    "caminho": "design-system/em-022-claro.html",
    "sistema": "Aura",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": null,
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system--em-022-escuro",
    "caminho": "design-system/em-022-escuro.html",
    "sistema": "Aura",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": null,
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system--email-claro",
    "caminho": "design-system/email-claro.html",
    "sistema": "Aura",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": null,
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system--email-escuro",
    "caminho": "design-system/email-escuro.html",
    "sistema": "Aura",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": null,
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-cadence--em-001-claro",
    "caminho": "design-system-cadence/em-001-claro.html",
    "sistema": "Cadence",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": null,
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-cadence--em-001-escuro",
    "caminho": "design-system-cadence/em-001-escuro.html",
    "sistema": "Cadence",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": null,
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-cadence--em-005-claro",
    "caminho": "design-system-cadence/em-005-claro.html",
    "sistema": "Cadence",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": null,
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-cadence--em-005-escuro",
    "caminho": "design-system-cadence/em-005-escuro.html",
    "sistema": "Cadence",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": null,
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-cadence--em-022-claro",
    "caminho": "design-system-cadence/em-022-claro.html",
    "sistema": "Cadence",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": null,
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-cadence--em-022-escuro",
    "caminho": "design-system-cadence/em-022-escuro.html",
    "sistema": "Cadence",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": null,
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-cadence--email-claro",
    "caminho": "design-system-cadence/email-claro.html",
    "sistema": "Cadence",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": null,
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-cadence--email-escuro",
    "caminho": "design-system-cadence/email-escuro.html",
    "sistema": "Cadence",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": null,
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--em-001-ai-designer-claro",
    "caminho": "design-system-trilhas/em-001-ai-designer-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": "AI Designer",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-ai-designer-escuro",
    "caminho": "design-system-trilhas/em-001-ai-designer-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": "AI Designer",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-analista-dados-claro",
    "caminho": "design-system-trilhas/em-001-analista-dados-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": "Analista de Dados",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-analista-dados-escuro",
    "caminho": "design-system-trilhas/em-001-analista-dados-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Analista de Dados",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-engenheiro-ia-claro",
    "caminho": "design-system-trilhas/em-001-engenheiro-ia-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": "Engenheiro de IA",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-engenheiro-ia-escuro",
    "caminho": "design-system-trilhas/em-001-engenheiro-ia-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Engenheiro de IA",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-n8n-claro",
    "caminho": "design-system-trilhas/em-001-n8n-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": "Automações n8n",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-n8n-escuro",
    "caminho": "design-system-trilhas/em-001-n8n-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Automações n8n",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-teal-claro",
    "caminho": "design-system-trilhas/em-001-teal-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": "Teal Asimov",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-001-teal-escuro",
    "caminho": "design-system-trilhas/em-001-teal-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Teal Asimov",
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-trilhas--em-005-ai-designer-claro",
    "caminho": "design-system-trilhas/em-005-ai-designer-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": "AI Designer",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-ai-designer-escuro",
    "caminho": "design-system-trilhas/em-005-ai-designer-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": "AI Designer",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-analista-dados-claro",
    "caminho": "design-system-trilhas/em-005-analista-dados-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": "Analista de Dados",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-analista-dados-escuro",
    "caminho": "design-system-trilhas/em-005-analista-dados-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": "Analista de Dados",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-engenheiro-ia-claro",
    "caminho": "design-system-trilhas/em-005-engenheiro-ia-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": "Engenheiro de IA",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-engenheiro-ia-escuro",
    "caminho": "design-system-trilhas/em-005-engenheiro-ia-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": "Engenheiro de IA",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-n8n-claro",
    "caminho": "design-system-trilhas/em-005-n8n-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": "Automações n8n",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-n8n-escuro",
    "caminho": "design-system-trilhas/em-005-n8n-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": "Automações n8n",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-teal-claro",
    "caminho": "design-system-trilhas/em-005-teal-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": "Teal Asimov",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-005-teal-escuro",
    "caminho": "design-system-trilhas/em-005-teal-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": "Teal Asimov",
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-trilhas--em-022-ai-designer-claro",
    "caminho": "design-system-trilhas/em-022-ai-designer-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": "AI Designer",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-ai-designer-escuro",
    "caminho": "design-system-trilhas/em-022-ai-designer-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": "AI Designer",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-analista-dados-claro",
    "caminho": "design-system-trilhas/em-022-analista-dados-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": "Analista de Dados",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-analista-dados-escuro",
    "caminho": "design-system-trilhas/em-022-analista-dados-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Analista de Dados",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-engenheiro-ia-claro",
    "caminho": "design-system-trilhas/em-022-engenheiro-ia-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": "Engenheiro de IA",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-engenheiro-ia-escuro",
    "caminho": "design-system-trilhas/em-022-engenheiro-ia-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Engenheiro de IA",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-n8n-claro",
    "caminho": "design-system-trilhas/em-022-n8n-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": "Automações n8n",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-n8n-escuro",
    "caminho": "design-system-trilhas/em-022-n8n-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Automações n8n",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-teal-claro",
    "caminho": "design-system-trilhas/em-022-teal-claro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": "Teal Asimov",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--em-022-teal-escuro",
    "caminho": "design-system-trilhas/em-022-teal-escuro.html",
    "sistema": "Trilhas",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": "Teal Asimov",
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-trilhas--email-ai-designer-claro",
    "caminho": "design-system-trilhas/email-ai-designer-claro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": "AI Designer",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-ai-designer-escuro",
    "caminho": "design-system-trilhas/email-ai-designer-escuro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": "AI Designer",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-analista-dados-claro",
    "caminho": "design-system-trilhas/email-analista-dados-claro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": "Analista de Dados",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-analista-dados-escuro",
    "caminho": "design-system-trilhas/email-analista-dados-escuro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": "Analista de Dados",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-engenheiro-ia-claro",
    "caminho": "design-system-trilhas/email-engenheiro-ia-claro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": "Engenheiro de IA",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-engenheiro-ia-escuro",
    "caminho": "design-system-trilhas/email-engenheiro-ia-escuro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": "Engenheiro de IA",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-n8n-claro",
    "caminho": "design-system-trilhas/email-n8n-claro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": "Automações n8n",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-n8n-escuro",
    "caminho": "design-system-trilhas/email-n8n-escuro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": "Automações n8n",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-teal-claro",
    "caminho": "design-system-trilhas/email-teal-claro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": "Teal Asimov",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-trilhas--email-teal-escuro",
    "caminho": "design-system-trilhas/email-teal-escuro.html",
    "sistema": "Trilhas",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": "Teal Asimov",
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-black--em-001-claro",
    "caminho": "design-system-black/em-001-claro.html",
    "sistema": "Black Friday",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "claro",
    "cor": null,
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-black--em-001-escuro",
    "caminho": "design-system-black/em-001-escuro.html",
    "sistema": "Black Friday",
    "peca": "EM-001",
    "nome": "Você sumiu…",
    "descricao": "Conversacional · Engajamento · Não aluno não engajado",
    "tema": "escuro",
    "cor": null,
    "assunto": "Você sumiu…"
  },
  {
    "id": "design-system-black--em-005-claro",
    "caminho": "design-system-black/em-005-claro.html",
    "sistema": "Black Friday",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "claro",
    "cor": null,
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-black--em-005-escuro",
    "caminho": "design-system-black/em-005-escuro.html",
    "sistema": "Black Friday",
    "peca": "EM-005",
    "nome": "Convite Exclusivo para você!",
    "descricao": "Conversacional · Pré-captura · Aluno Trilha",
    "tema": "escuro",
    "cor": null,
    "assunto": "Convite Exclusivo para você!"
  },
  {
    "id": "design-system-black--em-022-claro",
    "caminho": "design-system-black/em-022-claro.html",
    "sistema": "Black Friday",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "claro",
    "cor": null,
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-black--em-022-escuro",
    "caminho": "design-system-black/em-022-escuro.html",
    "sistema": "Black Friday",
    "peca": "EM-022",
    "nome": "Essa Black vai ser ao vivo",
    "descricao": "Conversacional · Captação · Não aluno não engajado",
    "tema": "escuro",
    "cor": null,
    "assunto": "Essa Black vai ser ao vivo"
  },
  {
    "id": "design-system-black--email-claro",
    "caminho": "design-system-black/email-claro.html",
    "sistema": "Black Friday",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "claro",
    "cor": null,
    "assunto": "Lorem ipsum"
  },
  {
    "id": "design-system-black--email-escuro",
    "caminho": "design-system-black/email-escuro.html",
    "sistema": "Black Friday",
    "peca": "Aplicação",
    "nome": "Vitrine de componentes",
    "descricao": "Todos os componentes do sistema num email com texto de exemplo.",
    "tema": "escuro",
    "cor": null,
    "assunto": "Lorem ipsum"
  }
];
